image: alpine:edge
before_script:
   - apk add --no-cache gcc cmake

stages:
  - build
  - unittests
  - tests

Build:
  stage: build
  script:
    - mkdir buildir
    - cd buildir
    - cmake ..
    - cmake --build .

Unit:
  stage: unittests
  script:
    - cd buildir && ctest -I 1,3,1

Tests:
  stage: tests
  script:
    - cd buildir && ctest
