image: alpine:edge
before_script:
   - apk add --no-cache build-base cmake gtest gtest-dev

stages:
  - build
  - test

.build:
  stage: build
  before_script:
    - apk add --no-cache ${COMPILER_PACKAGE}
    - mkdir -p buildir && cd buildir
  script:
    - cmake -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
    - cmake --build .
  artifacts:
    paths:
      - buildir

.unit_tests:
  stage: test
  script:
    - cd buildir
    - ctest -V -R 'unit:.*'

build-gcc-release:
  extends: .build
  variables:
    CMAKE_CXX_COMPILER: g++
    COMPILER_PACKAGE: gcc

test-gcc-release:
  extends: .unit_tests
  needs:
    - job: build-gcc-release
      artifacts: true

build-clang-release:
  extends: .build
  variables:
    CMAKE_CXX_COMPILER: clang++
    COMPILER_PACKAGE: clang

test-clang-release:
  extends: .unit_tests
  needs:
    - job: build-clang-release
      artifacts: true
